# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
